import { createBrowserClient } from '@supabase/ssr'

/**
 * Create a Supabase client for browser usage.
 * This client is used in client components and respects RLS policies.
 * 
 * Note: Database types will be auto-generated by Supabase CLI.
 * Run: supabase gen types typescript --project-id <project-ref> > lib/database.types.ts
 * 
 * For now, we use a generic type that can be extended once the database is set up.
 */
export function createClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  )
}

// Re-export types from @supabase/supabase-js for convenience
export type { User, Session, AuthChangeEvent } from '@supabase/supabase-js'
